In [32]:
import numpy
import os
xyz_file = numpy.genfromtxt(fname='water.xyz',skip_header=2,dtype='unicode')

In [33]:
symbols=xyz_file[:,0]
coordinates=xyz_file[:,1:]
coordinates =coordinates.astype(numpy.float)

In [34]:
print(symbols)

['O' 'H1' 'H2']


In [35]:
print(coordinates)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [36]:
for numA, atomA in enumerate(coordinates):
    for numB, atomB in enumerate(coordinates):
        if numB < numA:
            x_distance  = atomA[0]-atomB[0]
            y_distance  = atomA[1]-atomB[1]
            z_distance  = atomA[2]-atomB[2]
            distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
            if distance > 0 and distance < 1.5:
                print(F'{symbols[numA]} to {symbols[numB]}: {distance:.3f}')

H1 to O: 0.969
H2 to O: 0.969


In [38]:
def calculate_distance(atom1, atom2):
    x_distance  = atom1[0]-atom2[0]
    y_distance  = atom1[1]-atom2[1]
    z_distance  = atom1[2]-atom2[2]
    distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return distance

In [40]:
for numA, atomA in enumerate(coordinates):
    for numB, atomB in enumerate(coordinates):
        if numB < numA:
           distance_AB = calculate_distance(atomA, atomB)
           print(F'{symbols[numA]} to {symbols[numB]}: {distance_AB:.3f}')

H1 to O: 0.969
H2 to O: 0.969
H2 to H1: 1.527


In [64]:
def bond_check(bond_distance, minimum_value=0, maximum_value=1.5):
    if bond_distance > minimum_value and bond_distance < maximum_value:
        return True
    else:
        return False

In [67]:
for numA, atomA in enumerate(coordinates):
    for numB, atomB in enumerate(coordinates):
        if numB < numA:
            distance_AB = calculate_distance(atomA, atomB)
            if bond_check(distance_AB,maximum_value=3.0) is True:
                print(F'{symbols[numA]} to {symbols[numB]}: {distance_AB:.3f}')

H1 to O: 0.969
H2 to O: 0.969
H2 to H1: 1.527
